[package]
name = "bcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"

[dev-dependencies]
colored = "2.1.0"
similar = "2.5.0"
